: rmgroup.sh -- remove a group
:
: The strangeness following the -t option works because -t has space
: as a fill char in procopts. It means that you can say things like
:
:	rmgroup foo.bar baz.qux -d na
:
: and have inews interepret the -d option correctly.
:
inews -P -h -t cmsg rmgroup $* <<EOF
Subject: removal of $*
Control: rmgroup $*

This control message was generated by the rmgroup script.
EOF

: rmgroup.sh ends here
